### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by wxnnvs** [Eaglercraft-Archive/Eaglercraft-PBR-shaders#1]
Does someone have the source code for the latest version of eaglercraft and maybe an explanation/docs for how it works?

**Comment by radmanplays** [comment]
> 

source code:  https://github.com/Eaglercraft-Archive/Eaglercraftx-u19-source

**Comment by wxnnvs** [comment]
And how does it work exactly

**Comment by radmanplays** [comment]
> And how does it work exactly

idk you asked for it. there's no current documentation about the source code

**Comment by wxnnvs** [comment]
alr
